trigger:
  # - main
  # - master
  - none

pool:
  vmImage: ubuntu-latest

# edit these to match the names of your environments
variables:
  dev_env: <dev_env_name>
  test_env: <test_env_name>
  prod_env: <prod_env_name>

stages:
  - stage: "DeployDev"
    displayName: "Deploy to the dev environment"
    jobs:
      - deployment: DeployDev
        environment: $(dev_env)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deploy-template.yml
                  parameters:
                    azureEnvName: "$(dev_env)"
                    serviceConnection: "$(dev_env)" # if your service connection name is different from the environment name, change this

  - stage: "DeployTest"
    displayName: "Deploy to the test environment"
    dependsOn: DeployDev
    condition: succeeded('DeployDev')
    jobs:
      - deployment: DeployTest
        environment: $(test_env)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deploy-template.yml
                  parameters:
                    azureEnvName: "$(test_env)"
                    serviceConnection: "$(test_env)" # if your service connection name is different from the environment name, change this

  - stage: "DeployProd"
    displayName: "Deploy to the prod environment"
    dependsOn: DeployTest
    condition: succeeded('DeployTest')
    jobs:
      - deployment: DeployProd
        environment: $(prod_env)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deploy-template.yml
                  parameters:
                    azureEnvName: "$(prod_env)"
                    serviceConnection: "$(prod_env)" # if your service connection name is different from the environment name, change this
